version: '3'

services:

  djangoapp-cacheprep:
    build:
      context: .
      dockerfile: Dockerfile
    image: urself:latest
    container_name: djangoapp-cacheprep
    tty: true
    command: >
      sh -c "
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8002
      "
    restart: always
    ports:
      - "8002:8002"

