# Generated by Django 3.0 on 2020-07-09 12:58

import ApiHandler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Question')),
                ('img', models.FileField(upload_to=ApiHandler.models.question_image_path, verbose_name='Question Image')),
                ('tag', models.TextField(verbose_name='Question Tags')),
                ('posted_on', models.DateField(blank=True, null=True, verbose_name='Posted on')),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
